#!/bin/bash

./compile.sh

for ((n=0;n<10;n++))
do
#Seed randomizer
SEED=$(shuf -i 1-50000 -n 1);

#Cat randomizer
CATS=$(shuf -i 1-5 -n 1);

#Cheese randomizer
CHEESES=$(shuf -i 1-10 -n 1);

#Mode randomizer
MODE=$(shuf -i 0-1 -n 1);

#Depth randomizer
DEPTH=$(shuf -i 6-15 -n 1);

#Difficulty randomizer
DIFFICULTY=$(shuf -i 1-10 -n 1);
DIFFICULTY=$(python -c "print($DIFFICULTY/10.0)");

echo "======================================";
echo "./MiniMax_search $SEED $CATS $CHEESES $MODE $DEPTH $DIFFICULTY";
echo "======================================";

./MiniMax_search $SEED $CATS $CHEESES $MODE $DEPTH $DIFFICULTY;
done
